### ISSUE TITLE
PER2DET

### ISSUE THREAD

**Issue by rpoleski** [KeplerGO/pyke#102]
Hi,

Please have a look at this part of PER2DET:

[https://github.com/KeplerGO/PyKE/blob/master/pyke/kepfunc.py#L298#L313](https://github.com/KeplerGO/PyKE/blob/master/pyke/kepfunc.py#L298#L313)

All these lines are equivalent to:

```
        for (j, y) in enumerate(DATy):
            for (k, x) in enumerate(DATx):
                xx = x - OBJx[i]
                yy = y - OBJy[i]
```

Does anybody know why there are some many useless calculations? Is anybody sure that this code is correct?

CC: @barentsen @mirca

**Comment by mirca** [comment]
This part basically shifts the x and y coordinates to be centered on the centroid positions. This certainly can be done in a vectorized way. As I said in #109, we are working on reimplementing the PSF tools in PyKE, and this has already been addressed on our new implementation. Stay tuned for the upcoming release of PyKE :)
