### ISSUE TITLE
A few suggestions on kepprfphot

### ISSUE THREAD

**Issue by rpoleski** [KeplerGO/pyke#109]
1) The barytime vector in kepprfphot looses precision due to multiple floating-point operations and the printed output is slightly (O(10^-5 d)) different from naive expectations.
2) A large part of kepprfphot code is devoted to preparing the plots. 
  A) this should be a separate function because it's logically different task, 
  B) producing this plots should be an option, or there should be option to turn it off,
  C) points A) and B) may apply to other source files as well.
3) When I read some of the output files using astropy and access the tabulated data, I'm getting error message `WARNING: VerifyWarning: Invalid keyword for column 4: Column null option (TNULLn) is invalid for binary table columns of type 'E' (got -1).  The invalid value will be ignored for the purpose of formatting the data in this column. [astropy.io.fits.column]`. I have not in detail investigated the cause of this issue.

**Comment by mirca** [comment]
@rpoleski Thanks for the suggestions! We are currently in the process of reimplementing the PSF photometry capabilities available in PyKE to a more modular and user-friendly environment. These suggestions are certainly going to be taken into account.
