### ISSUE TITLE
Add ClusterTargetPixelFile class

### ISSUE THREAD

**Issue by mirca** [KeplerGO/pyke#122]
It would be useful to define such a class which would be able to compute approximate centroids for each object in the target pixel file. This would be very useful to the PRF photometry tools in order to get dynamic values for the initial guesses on the centroid and flux values.

The apertures around the objects in the TPF can be created with photutils, which may defined by the user.

This class should inherint from KeplerTargetPixelFile.

**Comment by barentsen** [comment]
Do we need a new class for this?  To get an estimate of source positions and fluxes of objects in a TPF, can we just add a `detect_sources()` method to `TargetPixelFile` which returns a table of the sources detected?  (e.g. using photutils)
