### ISSUE TITLE
Travis failure: `No module named oktopus`

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/pyke#123]
In fa68821620e7cd478e1e5d6f6e1f424493fe7ee9 I added `from .. import kepler_prf` to `test_imports.py`, which causes Travis to fail with message `ImportError: No module named oktopus`.

`oktopus` appears in `requirements.txt` so I don't understand the failure.

**Comment by mirca** [comment]
Yes, I'm investigating that as well.

It's weird because line 624 from the Travis log shows this:

```
Successfully installed astropy-2.0.2 autograd-1.1.13 cycler-0.10.0 future-0.16.0 matplotlib-2.0.2 oktopus-0.1.dev2 pyketools-3.0.0 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.2 scipy-0.19.1 tqdm-4.17.1
```

**Comment by mirca** [comment]
This has been fixed in [68dcac].(https://github.com/KeplerGO/oktopus/commit/68dcac991887259e0e29152ebcf6478a39892f14)
