### ISSUE TITLE
lightcurve.py should include a binning routine.

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/pyke#131]
kepfold has a nice function where it bins the data for the user. This would be a super useful function for lightcurve.py, particularly when used in conjunction with fold. It will make running transit fitting routines quicker (though less accurate) to have fewer points. It'll also look nicer for some lightcurves.

**Comment by barentsen** [comment]
Agreed, a `Lightcurve.bin()` method makes sense to me!  It may be possible to implement this with a numpy one-liner, but even so it is helpful to have it available in a handy `bin` function.

**Comment by barentsen** [comment]
This was added by #161.  Yay!  Closing.
