### ISSUE TITLE
Kepextract does not work on a single pixel anymore (?)

### ISSUE THREAD

**Issue by mirca** [KeplerGO/PyKE#14]
From keplergo@mail.arc.nasa.gov:

On Mon, Jun 5, 2017 at 8:53 AM, Mike Reed <mikereed@missouristate.edu> wrote:

>     Hi Geert,
>     Any update on this? Our 'big' issue is that kepextract used to work on a single pixel, but at
>     some point there was an update so it now requires 7 pixels. Our kepmask file used to look like 
>     b5|||851|139|4,4, but now we have to list 7 pixels, which is too large for this crowded field, and 
>     not necessary for original Kepler data. We want to extract single pixels, find which pixels really 
>     have the star (from SC data, we know that it is only 2-3 pixels for each rotation) and then 
>     extract only those pixels.

**Comment by mirca** [comment]
@barentsen this can be closed; I tested with different # pixels and replied Mike.

**Comment by barentsen** [comment]
Awesome, thank you @mirca! :strawberry:

**Comment by M-LED** [comment]
I am also having this issue. How did you go about fixing it?

**Comment by barentsen** [comment]
Hi @M-LED! This issue was fixed in June and should not appear if you are using a recent version of PyKE (e.g. v3.0).  Which version are you using?

**Comment by M-LED** [comment]
Hi @barentsen, thanks for replying. I'm using version 2.6.2 through Ureka

**Comment by barentsen** [comment]
@M-LED I do not remember how this issue was resolved (though @mirca might), but I would strongly encourage you to switch to PyKE v3.0!  The installation instructions and documentation are available at http://pyke.keplerscience.org

**Comment by mirca** [comment]
Hi @M-LED, thanks for getting in touch! As @barentsen said, we strongly recommend you to switch to PyKE 3.0! Bugs, such as the one you mentioned, were fixed and the performance was improved significantly.
