### ISSUE TITLE
Release PyKE v3.0.0

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/PyKE#17]
Thanks to @mirca's incredibly hard work, the master branch of PyKE is now compatible with Python 3 and no longer depends on PyRAF (cf #12), which were the key goals for "PyKe v3.0" aka "PyKE3".  This means we can now start planning the first official release of PyKE3!

Let's start by releasing a "3.0.beta" and announce it to a small audience on social media, followed by an official "3.0.0" a few weeks later announced on the website.

Tasks to complete ahead of the release are likely to include the following:
- [x] Review the documentation and its hosting
- [x] Edit the keplerscience website to reflect PyKE 3.0
- [x] Ensure installation and citation instructions in the README are up to date
- [x] Add the `kepdraw` tool [#18]
- [x] Add the `kepsff` tool [#19]
- [x] Add a simple tutorial to the sphinx docs that explains how to get a lightcurve from K2 pixels using `kepmask` + `kepextract` + `kepflatten` + `kepsff` + `kepdraw` (cf. https://keplerscience.arc.nasa.gov/PyKEprimerWalkthroughE.shtml)
- [x] Decide on a name for PyKE to use in PyPI (`pyke`, `pykep`, `pykepler` are all taken by others). Let's use `pyketools`?

**Comment by mirca** [comment]
+1 for ``pyke-kepler`` or even ``pyke3``.

**Comment by barentsen** [comment]
I think `pyketools` or `pyke3` may be the answer, because `pyke-kepler` gives the impression that it's not relevant for TESS.  I slightly favour `pyketools` to distinguish it from the existing `pyke` package on pypi (which we have nothing to do with).

**Comment by mirca** [comment]
I like ``pyketools``

**Comment by barentsen** [comment]
Tutorials have been added, so I released version `3.0.beta1` on pip today.  Procedure used:
```
python setup.py sdist
twine upload dist/pyketools-3.0b1.tar.gz
```

Next, I am going to do a bit more work reviewing the docs and testing tools before releasing 3.0.0.

**Comment by barentsen** [comment]
I restructured the sphinx docs over the weekend to make them clear ahead of the 3.0 release.  I pushed this straight to master because it'll be easier to fine-tune using separate PRs.  Please review!  One thing missing is a "contributing" page.

Finally, we need to update the kepler science website to reflect v3.0.  When that's done, we should be good to move from beta to a full release!

**Comment by barentsen** [comment]
I think we are good to release 3.0!  The only thing stopping me is #64, because it's a significant change to the API, but I think we can implement this today?

(Resolving parts of #63 would be nice too, but not essential.)

**Comment by mirca** [comment]
Yeah, #64 and #63 can be done today

**Comment by barentsen** [comment]
I have bumped the version to `3.0beta4` and pushed a new version to pypi.

I am thinking to release a new version at least every week for the foreseeable future, so that the version on pypi benefits from the various bugfixes that are being made on an almost daily basis now.  I propose to switch from `beta` to `3.0.0` at the occasion of our next big mailing list update, in ~14 days from now, which gives us a reason to include PyKE again in the mailing list update =)

@mirca What do you think of this strategy?

**Comment by mirca** [comment]
Sounds great, @barentsen!

**Comment by barentsen** [comment]
3.0.0 was released last week, congratulations everyone!
