### ISSUE TITLE
TPF should have a plotting function that shows the aperture mask

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/pyke#173]
Either as a keyword to the plot method or as its own method, we should be able to plot the aperture mask we're going to use.

**Comment by barentsen** [comment]
Agreed!

**Comment by mirca** [comment]
Added this in cbcd666c81a42aea6ebe3a6712d8dce37540ff81

before:
![screen shot 2018-01-18 at 12 43 36 pm](https://user-images.githubusercontent.com/13077051/35120528-42d6b7e2-fc4d-11e7-96d7-242138531841.png)

after:
![screen shot 2018-01-18 at 12 43 28 pm](https://user-images.githubusercontent.com/13077051/35120530-44a21332-fc4d-11e7-9e57-3095f02d4555.png)

**Comment by christinahedges** [comment]
OHHHHH that is beautiful. 👍 🏖 🐻 🐝

**Comment by barentsen** [comment]
:+1:
