### ISSUE TITLE
Add `kepdraw` to PyKE3

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/PyKE#18]
PyKE2 included a tool called `kepdraw` that was used to see what a lightcurve looks like.  It was not ported to PyKE3 as part of #12, but I do think we should consider including this tool in the first release of PyKE3.  This is because many users may not be comfortable with making a quick lightcurve plot from scratch, which may keep them from adopting PyKE3.

**Comment by barentsen** [comment]
`kepdraw` has been added to master in meanwhile and seems to work great!

We may think about adding a `--batch` or `--non-interactive` option to avoid the matplotlib window from opening so that `kepdraw` can be used in scripts.  However I'm not sure what the sensible name or default would be.  Thoughts?

**Comment by mirca** [comment]
How about ``--non-interactive``?

**Comment by barentsen** [comment]
Sounds good!  We can deal with this as part of #26 and close this issue.
