### ISSUE TITLE
`--help` should show the default argument values

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/PyKE#21]
I believe it is important that the `--help` strings show the default argument values.

For example, `$ kepflatten --help | grep datacol` currently shows:
`--datacol DATACOL     Name of data column to plot`
it would be helpful for users to show the default value, e.g.:
`--datacol DATACOL     Name of data column to plot (default: SAP_FLUX)`

This is not a requirement for the first release however.

**Comment by mirca** [comment]
+1 to also show the data type
