### ISSUE TITLE
Tutorial needs to include downloads of PRF files.

### ISSUE THREAD

**Issue by rawien** [KeplerGO/PyKE#30]
Tutorial call to kepprfphot requires a directory of prf files. The tutorial needs to give instructions for downloading the files.

> $ kepprfphot ktwo200071160-c91_lpd-targ-trimmed_3.fits  ktwo200071160-c91_trimmed_3_prfphot --columns 1013 --rows 918 --fluxes 18000 --prfdir ~/kplr2011265_prf --background --clobber --verbose

The exception the routine throws when you try without it is also unhelpful:

> KEPPRFPHOT started at: Thu Jun 29 16:51:12 2017
ERROR -- KEPIO.OPENFITS: cannot open ktwo200071160-c91_lpd-targ-trimmed_3.fits as a FITS file
ERROR -- KEPPRFPHOT: is ktwo200071160-c91_lpd-targ-trimmed_3.fits a Target Pixel File? 
Traceback (most recent call last):
  File "/usr/local/bin/kepprfphot", line 11, in <module>
    load_entry_point('pyke', 'console_scripts', 'kepprfphot')()
  File "/Users/christina/K2/PyKE/pyke/kepprfphot.py", line 1157, in kepprfphot_main
    args.overwrite, args.verbose, args.logfile)
  File "/Users/christina/K2/PyKE/pyke/kepprfphot.py", line 244, in kepprfphot
    kepmsg.err(logfile,message,verbose)
  File "/Users/christina/K2/PyKE/pyke/kepmsg.py", line 16, in err
    raise Exception(message)
Exception: ERROR -- KEPPRFPHOT: is ktwo200071160-c91_lpd-targ-trimmed_3.fits a Target Pixel File?

**Comment by mirca** [comment]
Fixed in [ed400da](https://github.com/KeplerGO/PyKE/commit/ed400da0ac411ed993b4ed488375bc6cea43a37b)
