### ISSUE TITLE
keprange not working properly

### ISSUE THREAD

**Issue by mirca** [KeplerGO/PyKE#41]

**Comment by mirca** [comment]
This was fixed in [562c72b](https://github.com/KeplerGO/PyKE/commit/562c72b87e44d3e49a66f54922349b96eef2cbb0). I found that Python 2.7 is not happy with the MacOSX mpl backend. In Python 3, it works with whatever backend.

**Comment by barentsen** [comment]
:+1:

**Comment by gully** [comment]
Kepmask is has a similar backend problem.  I found that using `TkAgg` backend made kepmask work for me.

**Comment by gully** [comment]
oh wait, this is redundant with #48
