### ISSUE TITLE
kepmask: doesn't work with macosx backend on @gully's machine

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/PyKE#48]
We may want to consider enforcing e.g. TkAgg as the backend.

**Comment by gully** [comment]
I think the correct solution is to force TkAgg.

**Comment by barentsen** [comment]
I have a similar issue with `keprange`, which does not work on `Qt5Agg` but does work with `TkAgg`.  We are going to want to either debug this or force the use of TkAgg.

**Comment by barentsen** [comment]
@mirca implemented a workaround by forcing the use of `TkAgg` at the top of `__init__.py`.  This won't work if a user already has a backend initialized in their kernel, but it's good enough for v3.0.
