### ISSUE TITLE
Offer the possibility to export the data to a time series database

### ISSUE THREAD

**Issue by PierreZ** [KeplerGO/PyKE#58]
Hi,

I'm new to astronomy analysis, so maybe my need is fulfilled with another software, please let me know 😄 

I would like to give a try analyzing Kepler time series with [Warp10](http://www.warp10.io/), an open source time series database that has huge analysis capabilities. For this, I need to export Kepler FITS time series to the Warp10 [Warp10 Input Format](http://www.warp10.io/apis/gts-input-format/).

I saw that there is a task called [kepconvert](http://pyke.readthedocs.io/en/latest/api/kepconvert.html), should I add the option there or create a new task for TS export? Other people might want to export to another standard.

**Comment by barentsen** [comment]
Hi @PierreZ, thanks for your feedback!  I haven't heard anyone use Warp10 in astronomy before.  We're definitely interested to hear about its benefits -- will you be sharing your experiences on a blog?

For now I would recommend creating a small standalone tool that takes the output from `kepconvert` and transforms it into the format needed for Warp10.  We'd only want to have this format supported by `kepconvert` if we are certain that this feature will be used often enough to justify maintaining and testing it.

PS: I'm not a fan of the current output of `kepconvert`.  We may want to change it ahead of the upcoming 3.0 release to produce a proper csv file with a header, which may make the conversion to Warp10 input much easier?

**Comment by PierreZ** [comment]
Hi @barentsen, thanks for your reply! 

Warp10 is not quite famous at the moment, but I think it's the right solution for TS analysis (I already wrote a [blogpost](https://pierrez.github.io/blog/engage-maximum-warp-speed-in-time-series-analysis-with-warpscript/) about it). In the same spirit, I'll probably share my results into a blogpost or more depending of the results 😄 

Having a CSV to parse would be awesome 👍  Do you want some help on #59 ?

**Comment by barentsen** [comment]
@PierreZ You're certainly welcome to work on #59 if you want to!  If you do, please keep the issue updated of your status -- we may work on this ahead of the 3.0 release otherwise.  Thanks!

**Comment by mirca** [comment]
Looks like we are very happy with ``fits2csv`` added by @PierreZ  =)

**Comment by PierreZ** [comment]
Cool, I'm also really happy with it :sunglasses: I just need to take care of the BJD time (proposal at #71), and I should be ready to start the analysis :+1:
