### ISSUE TITLE
Have `kepconvert` produce CSV output

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/PyKE#59]
I propose the following improvements to `kepconvert`:
* add a header line to the ascii output;
* choose a sensible default for the output file name (e.g. infile+".txt");
* set a sensible default for the default conversion (fits2asc?);
* add support for csv;
* improve the description of the output format in the `--help` string.

**Comment by barentsen** [comment]
This proposal is triggered by #58.

**Comment by PierreZ** [comment]
I can give a try to the CSV support
