### ISSUE TITLE
Update CLI descriptions in docstrings

### ISSUE THREAD

**Issue by gully** [KeplerGO/PyKE#63]
Minor notes on the CLI when you execute `--help`.

1. In `kepwindow --help` "Name of input file" is too general.  Should say some more concrete information, FITS only, or ascii too?
2. In `keptrim --help` the command line argument `--kepid` refers only to "the Kepler ID number from the Kepler Input Catalog".  What about K2 EPIC numbers?
3. In `kepstitch --help`, "Append multiple month short cadence and/or multiple quarter long cadence data" should have a qualifier that it's for the original Kepler data only.  Also: `--outfile OUTFILE` is an *optional* command line argument, which differs from most other CLI behaviors.  (I actually prefer the default outfile name strategy.)
4. Why does `kepstddev` output an outfile if it just calculates CDPP?  Does it modify the header or something?
5. In `kepsff`, repeated word "for":
> --npoly_arfl NPOLY_ARFL
                        Order of ploynomial ~~for~~ for arclength-flux calibration
                        (default: 3)

6.  In `kepsff`, the name `--plotres`, does not seem to match the description:
>   Save hardcopies of the plots?

7. More explanation needed for how kepprf differs from kepprfphot
8. `keppca` must require the CBV files, right? This could be noted in the CLI.
9.  In `kephead`: "Snippet of keyword name" could be "full or partial keyword name"
10. In `kepft` CLI "search period" is a bit misleading, since nothing is being "searched".  
11. In `kepfold`, many of the CLI optional arguments refer to binning properties, which are only needed if binning is selected.  Can that be indicated somehow?
12. In `kepflatten`: the description is wrong:
> Remove or replace data outliers from a time series

**Comment by barentsen** [comment]
All these sound like items we should fix.

For 3. (`kepstitch`): it could be useful for K2 too, in Campaign 9, which was released as two separate half-campaigns (91 and 92).

**Comment by mirca** [comment]
@gully thanks Gully!

**Comment by gully** [comment]
13. In `kepdiffim`, the description says:
> Difference imaging of pixels within a target mask

But it does not indicate whether a mask file is required.

**Comment by gully** [comment]
14. In `kepbls` CLI the task description is incorrect in argparse:
> Remove or replace data outliers from a time series

**Comment by gully** [comment]
15. In `kepmask` the CLI indicates that plotfile accepts a default value, but actually requires an argument
>: error: argument --plotfile: expected one argument

**Comment by mirca** [comment]
closing this since most of it has been fixed or reported as separate issues
