### ISSUE TITLE
speeding up kepclip

### ISSUE THREAD

**Issue by jjhermes** [KeplerGO/PyKE#84]
Big props on how much faster kepextract is on short-cadence data with PyKE 3.0, thanks for that!

I've found another (less significant) bottleneck: kepclip takes A LOT longer than it should if it's just removing entries in a time series (up to a few minutes on a relatively new MacBook Pro). I wonder if you could investigate why kepclip is so SLOW on short-cadence data. kepstitch runs considerably faster for what should be essentially the same arithmetic. Thanks!

**Comment by barentsen** [comment]
That's a great piece of feedback, thank you, we'll look into it!

**Comment by mirca** [comment]
hey @jjhermes, we merged a patch which sped up kepclip! Have a try on the new version and let us know what you think, please
