### ISSUE TITLE
Comments on docs and some warning/error messages

### ISSUE THREAD

**Issue by gully** [KeplerGO/PyKE#85]
Some very minor edits to docs:

### Docs
- [x] In `install.html` after the `make html` instructions, `_build` ➡️  `build`.
- [x] `install.html` directs users to `pyke.readthedocs.io`; should it direct to `pyke.keplerscience.org` instead?  
- [x] In `kepextract` docstring, consider: "The pipeline" ➡️ "The Kepler pipeline"
- [x] In `kepextract` docstring, consider placing "Light curves for extended sources..." on its own line.
- [x] In `kepextract` docstring: "one of three options::" ➡️  "one of three options:"
- [x] In `kepextract` docstring: "pixels in within" -> "pixels within"
- [x] In `kepextract` docstring: "warnings to the shell" -> "warnings print to the shell"
- [x] Possible broken link: "We recommend the tools `ds9"

### Warnings
- [x] `invalid value encountered in double_scalars` while running kepextract
- [ ] `tqdm` jumps a line when warnings appear.  Is there an option to detect and enable Jupyter notebook support similar to astropy Progressbar?
- [ ] Kepextract prints information (e.g. `Aperture photometry...`) even in `verbose=False` mode. Should it?

**Comment by barentsen** [comment]
* All docs edit sound good!
* We should definitely look into fixing or suppressing some of the useless invalid value warnings (likely due to NaNs in the data etc);
* I think all tools should print a minimum set of useful feedback even without `verbose=True`, but we could look into adding a `quiet` parameter or make the logging more configurable otherwise using Python's logging framework.

**Comment by mirca** [comment]
Yep, sounds great!

**Comment by mirca** [comment]
We can use something like: ``np.seterr(divide='ignore', invalid='ignore')`` to suppress warnings

**Comment by gully** [comment]
TkAGG appears to be misbehaving while attempting to use `kepdraw`, following the [Quickstart guide](http://pyke.readthedocs.io/en/latest/quickstart.html)

```bash
$ kepdraw kplr008462852-2013098041711_lpd-targ-kepextract.fits
WARNING: VerifyWarning: Invalid keyword for column 4: Column null option (TNULLn) is invalid for binary table columns of type 'E' (got -1).  The invalid value will be ignored for the purpose of formatting the data in this column. [astropy.io.fits.column]
Found the following flux columns: SAP_FLUX, SAP_FLUX_ERR, PDCSAP_FLUX, PDCSAP_FLUX_ERR, RAW_FLUX
Using data column PDCSAP_FLUX on the plot...
Writing output file kplr008462852-2013098041711_lpd-targ-kepextract-kepdraw.png...
Traceback (most recent call last):
  File "/Users/obsidian/anaconda3/bin/kepdraw", line 11, in <module>
    load_entry_point('pyketools', 'console_scripts', 'kepdraw')()
  File "/Users/obsidian/GitHub/PyKE/pyke/kepdraw.py", line 344, in kepdraw_main
    args.verbose, args.logfile)
  File "/Users/obsidian/GitHub/PyKE/pyke/kepdraw.py", line 276, in kepdraw
    plt.show()
  File "/Users/obsidian/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 253, in show
    return _show(*args, **kw)
  File "/Users/obsidian/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 193, in __call__
    self.mainloop()
  File "/Users/obsidian/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 71, in mainloop
    Tk.mainloop()
  File "/Users/obsidian/anaconda3/lib/python3.6/tkinter/__init__.py", line 557, in mainloop
    _default_root.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by gully** [comment]
The kepcotrend documentation seems a bit out of date:

> While GOs, KASC members and archive users wait for the Kepler project to release quarters of data, they do not have access to all the light curve data

and:

> More details on the method used to generate these basis vectors will be provided in the Kepler Data Processing Handbook soon, but until that time, a summary of the method is given here.

**Comment by gully** [comment]
The API documentation generates locally (`make html`), but does not show up on the web:

http://pyke.keplerscience.org/en/latest/api/kepmask.html

**Comment by gully** [comment]
More generally, it looks like the docs online are not updated.  [Example 1 tutorial](http://pyke.keplerscience.org/en/latest/tutorials/aperture-photometry-in-k2.html) has an old image `kepmask1.png`, while my local version shows a new one `kepmask2.png`.

**Comment by gully** [comment]
I got a recursion error while using `kepmask`:

```python
[...]

  File "/Users/obsidian/GitHub/PyKE/pyke/kepmask.py", line 414, in clicker6
    plotimage()
  File "/Users/obsidian/GitHub/PyKE/pyke/kepmask.py", line 202, in plotimage
    plt.axes([0.73, 0.09, 0.25, 0.4])

[...]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by mirca** [comment]
Great! I'm going to close this because the remaining points already have their own tickets. Thanks @gully
