### ISSUE TITLE
Clarify the distinction between command-line tools and Python code

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/PyKE#94]
It was pointed out to me by a beginning user that, e.g. in the first tutorial ( http://pyke.readthedocs.io/en/latest/tutorials/aperture-photometry-in-k2.html ), it is not clear that the `wget` and `kepmask` are command-line tools that need to be executed in the shell rather than a Python environment.  Let's make sure this is always clear!

**Comment by mirca** [comment]
absolutely!
