### ISSUE TITLE
difference between PRF2DET2 and PRF2DET

### ISSUE THREAD

**Issue by rpoleski** [KeplerGO/PyKE#99]
Hi @barentsen and @mirca,

It seems for me there's a bug in PRF2DET() function of kepfunc.py file. The second last line says:

`PRFfit[j, k] += PRFfit[j,k] + splineInterpolation(dy * wy, dx * wx) * flux[i]`

It like "x += x + dx". Previous function in the same file has:

`PRFfit[j, k] = PRFfit[j, k] + splineInterpolation(dy, dx) * flux[i]`

which looks normal. Can you comment on this?

**Comment by mirca** [comment]
Hi @rpoleski, thanks for the catch!

Additionally, the function ``PRF2DET2``, other than being defined, is not used anywhere else.
